"""2FA Enabled attribute

Revision ID: 2098ebea90d6
Revises: e656a82cffe1
Create Date: 2025-06-20 23:40:06.383976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2098ebea90d6'
down_revision = 'e656a82cffe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is2fa_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is2fa_enabled')

    # ### end Alembic commands ###
