"""Tournament models and mission configuration

Revision ID: 3af4d198a273
Revises: c2bdfbbc0c87
Create Date: 2025-06-15 22:04:53.261081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af4d198a273'
down_revision = 'c2bdfbbc0c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tournament_type', sa.Enum('RACE', 'BOAT', 'LAKE', 'MORAY', name='tournamenttype'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament'))
    )
    op.create_table('tournament_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='tournamentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name=op.f('fk_tournament_history_tournament_id_tournament')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_history'))
    )
    op.create_table('tournament_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_history_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('participation_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_tournament_log_player_id_player')),
    sa.ForeignKeyConstraint(['tournament_history_id'], ['tournament_history.id'], name=op.f('fk_tournament_log_tournament_history_id_tournament_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_log'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.Enum('NEW_FRIEND', 'TOURNAMENT', 'VISIT_AN_AREA', 'FISHING_LOG', 'FISHDEX', 'HOMEFISH', 'UPGRADE', 'HOMEPOINTS', name='tasktype'), nullable=False))
        batch_op.add_column(sa.Column('goal_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('upgrade_type', sa.Enum('FishingLine', 'MoneyTree', name='upgradetype'), nullable=True))
        batch_op.add_column(sa.Column('special_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_task_special_location_id_special_location'), 'special_location', ['special_location_id'], ['id'])

    with op.batch_alter_table('task_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_progress_count', sa.Integer(), nullable=False))
        batch_op.drop_column('catched_fish_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catched_fish_amount', sa.INTEGER(), nullable=False))
        batch_op.drop_column('current_progress_count')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_special_location_id_special_location'), type_='foreignkey')
        batch_op.drop_column('special_location_id')
        batch_op.drop_column('upgrade_type')
        batch_op.drop_column('goal_count')
        batch_op.drop_column('task_type')

    op.drop_table('tournament_log')
    op.drop_table('tournament_history')
    op.drop_table('tournament')
    # ### end Alembic commands ###
