"""FruitCombination model added

Revision ID: 3e23415fbb1b
Revises: 3fea1c1f7bb1
Create Date: 2025-06-14 16:59:16.729534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e23415fbb1b'
down_revision = '3fea1c1f7bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit_combination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fruit1_id', sa.Integer(), nullable=False),
    sa.Column('fruit2_id', sa.Integer(), nullable=False),
    sa.Column('fruit3_id', sa.Integer(), nullable=False),
    sa.Column('reward_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['fruit1_id'], ['fruit.id'], ),
    sa.ForeignKeyConstraint(['fruit2_id'], ['fruit.id'], ),
    sa.ForeignKeyConstraint(['fruit3_id'], ['fruit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_fruit_combination',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fruit_combination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fruit_combination_id'], ['fruit_combination.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'fruit_combination_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_fruit_combination')
    op.drop_table('fruit_combination')
    # ### end Alembic commands ###
