"""Relation between FruitCombinaton and Player

Revision ID: b60d9641531d
Revises: 3e23415fbb1b
Create Date: 2025-06-14 19:08:37.920103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60d9641531d'
down_revision = '3e23415fbb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_account_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_account_username'), ['username'])

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_area_area_id'), ['area_id'])

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_club_leader_id'), ['leader_id'])

    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fruit_combination_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_fish_fruit_combination_id_fruit_combination'), 'fruit_combination', ['fruit_combination_id'], ['id'])
        batch_op.drop_column('fruit_combination_count_to_unlock')

    with op.batch_alter_table('fishing_line', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_fishing_line_player_id'), ['player_id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_item_decoration_id'), ['decoration_id'])

    with op.batch_alter_table('money_tree', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_money_tree_player_id'), ['player_id'])

    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_outfit_outfit_template_id'), ['outfit_template_id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_player_homeplan_id'), ['homeplan_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_player_outfit_id'), ['outfit_id'])

    with op.batch_alter_table('player_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_player_settings_player_id'), ['player_id'])

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_player_stats_player_id'), ['player_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_stats_player_id'), type_='unique')

    with op.batch_alter_table('player_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_settings_player_id'), type_='unique')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_outfit_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_player_homeplan_id'), type_='unique')

    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_outfit_outfit_template_id'), type_='unique')

    with op.batch_alter_table('money_tree', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_money_tree_player_id'), type_='unique')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_item_decoration_id'), type_='unique')

    with op.batch_alter_table('fishing_line', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fishing_line_player_id'), type_='unique')

    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fruit_combination_count_to_unlock', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_fish_fruit_combination_id_fruit_combination'), type_='foreignkey')
        batch_op.drop_column('fruit_combination_id')

    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_club_leader_id'), type_='unique')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_area_area_id'), type_='unique')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_account_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_account_email'), type_='unique')

    # ### end Alembic commands ###
