"""Add collection model and relationships

Revision ID: c2bdfbbc0c87
Revises: b60d9641531d
Create Date: 2025-06-14 22:02:02.094621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bdfbbc0c87'
down_revision = 'b60d9641531d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Fruit', 'Fish', 'Decoration', name='collectiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    op.create_table('collection_fruit',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_fruit_collection_id_collection')),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruit.id'], name=op.f('fk_collection_fruit_fruit_id_fruit')),
    sa.PrimaryKeyConstraint('collection_id', 'fruit_id', name=op.f('pk_collection_fruit'))
    )
    op.create_table('collection_decoration',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('decoration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_decoration_collection_id_collection')),
    sa.ForeignKeyConstraint(['decoration_id'], ['decoration.id'], name=op.f('fk_collection_decoration_decoration_id_decoration')),
    sa.PrimaryKeyConstraint('collection_id', 'decoration_id', name=op.f('pk_collection_decoration'))
    )
    op.create_table('decoration_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decor_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_decoration_record_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decoration_record'))
    )
    op.create_table('fruit_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_fruit_record_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fruit_record'))
    )
    op.create_table('collection_fish',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_fish_collection_id_collection')),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], name=op.f('fk_collection_fish_fish_id_fish')),
    sa.PrimaryKeyConstraint('collection_id', 'fish_id', name=op.f('pk_collection_fish'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_fish')
    op.drop_table('fruit_record')
    op.drop_table('decoration_record')
    op.drop_table('collection_decoration')
    op.drop_table('collection_fruit')
    op.drop_table('collection')
    # ### end Alembic commands ###
