"""Player modeline last_activity_date alanı eklendi

Revision ID: 65e668ad3010
Revises: 1c32b8bb5935
Create Date: 2025-06-03 18:39:01.530259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e668ad3010'
down_revision = '1c32b8bb5935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('last_activity_date')

    # ### end Alembic commands ###
