"""AccountRole table

Revision ID: e656a82cffe1
Revises: 3af4d198a273
Create Date: 2025-06-19 21:19:27.607788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e656a82cffe1'
down_revision = '3af4d198a273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_role')),
    sa.UniqueConstraint('name', name=op.f('uq_account_role_name'))
    )
    op.create_table('account_roles',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_account_roles_account_id_account')),
    sa.ForeignKeyConstraint(['account_role_id'], ['account_role.id'], name=op.f('fk_account_roles_account_role_id_account_role')),
    sa.PrimaryKeyConstraint('account_id', 'account_role_id', name=op.f('pk_account_roles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_roles')
    op.drop_table('account_role')
    # ### end Alembic commands ###
